// <-- This file is generated by xedithor. Don't edit this --> 

package com.game.test;

interface SPRITE_
{
	public final static int FRAME_COUNT = 0;

	public final static int ANIM_COUNT = 0;
}
