// <-- This file is generated by xedithor. Don't edit this --> 

package com.game.test;

interface SPRITE_BGMAIN
{
	public final static int FRM_BG_0 = 0;
	public final static int FRAME_COUNT = 1;

	public final static int ANIM_0 = 0;
	public final static int ANIM_COUNT = 1;
}
