// <-- This file is generated by xedithor. Don't edit this --> 

package com.game.test;

interface DATA_SPRITE
{
	public final static int SPR_BGMAIN = 1;
	public final static int SPR_SOLDIER = 2;
	public final static int COUNT = 3;
}
